- name: check if tomcat is running
  raw: ps -ef | grep {{ instance_path }} | grep java | grep -v grep | wc -l
  register: instance_status

- debug: msg="{{instance_status.stdout_lines }}"

- name: get pid
  raw: ps -ef | grep {{instance_path}} | grep java | grep -v grep | awk '{print $2}'
  register: pid
  when: instance_status.stdout_lines > 0
- debug: msg="{{pid.stdout_lines}}"


- name: shutdown instance
  shell: "source /etc/profile; {{instance_path}}/bin/shutdown.sh"
  ignore_errors: yes
  when: instance_status.stdout_lines > 0
